version: '3.8'

services:
  compiler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test-results:/app/test-results
    environment:
      - TERM=xterm-color 
    tty: true  
