site_name: Compilador C em Português
site_description: Documentação do compilador para a linguagem C traduzida para português
site_author: Grupo 5
repo_url: https://github.com/ccarlaa/Compiladores---Grupo-5
repo_name: ccarlaa/Compiladores---Grupo-5

theme:
  name: material
  language: pt-BR
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Início: index.md
  - Guia do Usuário:
      - Instalação: guia-usuario/instalacao.md
      - Uso Básico: guia-usuario/uso-basico.md
      - Exemplos: guia-usuario/exemplos.md
  - Documentação Técnica:
      - Visão Geral: documentacao-tecnica/visao-geral.md
      - Análise Léxica: documentacao-tecnica/analise-lexica.md
      - Análise Sintática: documentacao-tecnica/analise-sintatica.md
      - Gramática: documentacao-tecnica/gramatica.md
      - Testes: documentacao-tecnica/testes.md
      - CI/CD: documentacao-tecnica/ci-cd.md
      - Evolução: documentacao-tecnica/evolucao.md
      - Decisões Técnicas: documentacao-tecnica/decisoes-tecnicas.md
  - Contribuição: contribuicao.md
  - Atas de Reunião:
      - Visão Geral: atas-reuniao/index.md
      - Reunião 1: atas-reuniao/reuniao-01.md
      - Reunião 2: atas-reuniao/reuniao-02.md
      - Reunião 3: atas-reuniao/reuniao-03.md
      - Reunião 4: atas-reuniao/reuniao-04.md
      - Reunião 5: atas-reuniao/reuniao-05.md
      - Reunião 6: atas-reuniao/reuniao-06.md
  - Sprints: sprints/index.md
  - Referências: referencias/referencias.md
