name: Release - Binários Multiplataforma

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    name: Build para ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows
            executable: compilador.exe
            artifact: tradutor-windows
          - os: ubuntu-latest
            name: Linux
            executable: compilador
            artifact: tradutor-linux
          - os: macos-latest
            name: macOS
            executable: compilador
            artifact: tradutor-macos
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Setup MinGW (Windows)
      if: matrix.os == 'windows-latest'
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        
    - name: Instalar dependências (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y build-essential
      
    - name: Verificar ferramentas
      run: gcc --version
      
    - name: Compilar projeto
      run: |
        gcc -std=c99 -Wall -Wextra -DMANUAL_MODE -O2 -s -o ${{ matrix.executable }} src/main.c
      shell: bash
      
    - name: Testar executável
      run: |
        if [ -f "${{ matrix.executable }}" ]; then
          echo "✓ Executável criado: ${{ matrix.executable }}"
          ./${{ matrix.executable }} tests/test_01_basic.c > test_output.txt
          echo "✓ Teste básico executado"
        else
          echo "✗ Falha na criação do executável"
          exit 1
        fi
      shell: bash
      
    - name: Criar pacote
      run: |
        mkdir -p release
        cp ${{ matrix.executable }} release/
        cp README.md release/
        cp -r tests release/
        
        # Criar arquivo de informações
        echo "Tradutor C para Portugol - ${{ matrix.name }}" > release/INFO.txt
        echo "Versão: ${{ github.ref_name }}" >> release/INFO.txt
        echo "Build: $(date)" >> release/INFO.txt
        echo "Sistema: ${{ matrix.name }}" >> release/INFO.txt
        echo "" >> release/INFO.txt
        echo "Para usar:" >> release/INFO.txt
        echo "  ./${{ matrix.executable }} arquivo.c" >> release/INFO.txt
        echo "  ./${{ matrix.executable }} arquivo.c -o saida.ptg" >> release/INFO.txt
      shell: bash
      
    - name: Upload do artefato
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: release/
        retention-days: 90

  create-release:
    needs: build-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Download todos os artefatos
      uses: actions/download-artifact@v4
      
    - name: Criar arquivos ZIP
      run: |
        zip -r tradutor-windows.zip tradutor-windows/
        tar -czf tradutor-linux.tar.gz tradutor-linux/
        tar -czf tradutor-macos.tar.gz tradutor-macos/
        
    - name: Criar release
      uses: softprops/action-gh-release@v1
      with:
        name: "Tradutor C para Portugol ${{ github.ref_name }}"
        body: |
          ## 🎉 Nova versão do Tradutor C para Portugol
          
          Esta release inclui binários compilados para Windows, Linux e macOS.
          
          ### 📦 Downloads Disponíveis
          - **Windows**: `tradutor-windows.zip`
          - **Linux**: `tradutor-linux.tar.gz` 
          - **macOS**: `tradutor-macos.tar.gz`
          
          ### 🚀 Como usar
          1. Baixe o arquivo para seu sistema operacional
          2. Extraia o arquivo
          3. Execute: `./compilador arquivo.c` (Linux/Mac) ou `compilador.exe arquivo.c` (Windows)
          
          ### ✨ Funcionalidades
          - Tradução de código C para Portugol
          - Suporte multiplataforma  
          - Modo standalone (sem dependências)
          - Suite completa de testes incluída
          
          ### 🧪 Testes
          Todos os builds passaram nos testes automatizados em:
          - ✅ Windows (MinGW)
          - ✅ Linux (GCC)
          - ✅ macOS (Clang)
          
        files: |
          tradutor-windows.zip
          tradutor-linux.tar.gz
          tradutor-macos.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
